services:
  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64       # 👈 add this line
    restart: always
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    networks:
      - keycloak-net

networks:
  keycloak-net:
    external: true