services:
  mailhog:
    image: mailhog/mailhog
    container_name: smtp
    platform: linux/amd64
    restart: always
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    networks:
      - local-network

networks:
  local-network:
    external: true